swagger: "2.0"
definitions:
  serviceTerm:
    x-jcloud-module: renewal
    title: ServiceTerm
    type: object
    properties:
      value:
        type: string
      description:
        type: string
